export const courseCatalog = [
  { number: '201', title: 'DATA STRUCTURES', types: ['LOGIC', 'SYSTEMS'], credits: '3 UNITS', level: 'CORE', category: 'ALGORITHM COURSE', color: 'bg-cyan-400', description: 'TRAINS THE MIND TO ORGANIZE DATA, ANALYZE COMPLEXITY, AND CHOOSE THE RIGHT STRUCTURE FOR THE JOB.' },
  { number: '202', title: 'OBJECT-ORIENTED PROGRAMMING', types: ['JAVA', 'DESIGN'], credits: '3 UNITS', level: 'CORE', category: 'PROGRAMMING COURSE', color: 'bg-purple-300', description: 'BUILDS REUSABLE SOFTWARE THROUGH ABSTRACTION, ENCAPSULATION, INHERITANCE, AND CLEAR INTERFACES.' },
  { number: '203', title: 'COMPUTER ARCHITECTURE', types: ['HARDWARE', 'SYSTEMS'], credits: '3 UNITS', level: 'CORE', category: 'SYSTEMS COURSE', color: 'bg-amber-400', description: 'EXAMINES THE PATH FROM INSTRUCTIONS TO HARDWARE, INCLUDING MEMORY, PROCESSORS, AND LOW-LEVEL EXECUTION.' },
  { number: '204', title: 'CONCURRENCY', types: ['SYSTEMS', 'C++'], credits: '3 UNITS', level: 'ADVANCED', category: 'SYSTEMS COURSE', color: 'bg-emerald-400', description: 'STUDIES COORDINATION BETWEEN EXECUTING TASKS, WITH CAREFUL ATTENTION TO SHARED STATE, TIMING, AND SAFETY.' },
  { number: '205', title: 'DATABASE SYSTEMS', types: ['SQL', 'DATA'], credits: '3 UNITS', level: 'CORE', category: 'DATA COURSE', color: 'bg-cyan-400', description: 'COVERS RELATIONAL DATA MODELING, QUERIES, AND THE RELIABLE STORAGE OF INFORMATION USED BY SOFTWARE.' },
  { number: '206', title: 'WEB SYSTEMS', types: ['REACT', 'WEB'], credits: '3 UNITS', level: 'APPLIED', category: 'APPLICATION COURSE', color: 'bg-purple-300', description: 'CONNECTS USER INTERFACES, SERVER LOGIC, AND DEPLOYMENT INTO PRACTICAL WEB EXPERIENCES.' },
  { number: '207', title: 'MACHINE LEARNING', types: ['PYTHON', 'AI'], credits: '3 UNITS', level: 'APPLIED', category: 'INTELLIGENCE COURSE', color: 'bg-amber-400', description: 'USES DATA, MODELS, AND EVALUATION TO BUILD SOFTWARE THAT CAN RECOGNIZE PATTERNS AND MAKE INFORMED PREDICTIONS.' },
  { number: '208', title: 'EMBEDDED SYSTEMS', types: ['C++', 'HARDWARE'], credits: '3 UNITS', level: 'APPLIED', category: 'HARDWARE COURSE', color: 'bg-emerald-400', description: 'BRINGS SOFTWARE TO THE DEVICE LEVEL, WHERE CODE WORKS DIRECTLY WITH SENSORS, TIMING, AND REAL-WORLD SIGNALS.' },
]

export const experienceEntries = [
  { number: '001', title: 'SOFTWARE ENGINEER INTERN', types: ['DEV', 'CLOUD'], duration: 'MAY 2024 – AUG 2024', location: 'CÚCUTA, COLOMBIA', organization: 'DIMELCO S.A.S', category: 'ENGINEERING ROLE', description: 'Developed prototype landing page and employee system across multiple cross-functional teams using JavaScript, HTML, CSS, React, and TypeScript, resulting in faster website production and reduced single employee management time. Engineered Python RESTful APIs and SQL queries, validating them for production through GitHub actions CI/CD pipelines and DockerContainers in an AWS environment prior to customer deployment and code review. Mentored by senior engineers through weekly sessions for the process of documenting and implementing LLM and agentic AI-assisted work for daily tasks while receiving feedback on my personal work being reported.' },
  { number: '002', title: 'FREELANCE SOFTWARE ENGINEER', types: ['DEV', 'CLOUD'], duration: 'JUN 2026 – AUG 2026', location: 'REMOTE', organization: 'SELF-EMPLOYED', category: 'ENGINEERING ROLE', description: 'SHIPPED WEB PROTOTYPES AND EMPLOYEE-MANAGEMENT EXPERIENCES WITH MODERN FRONTEND AND BACKEND TOOLS.' },
  { number: '003', title: 'LEARNING ASSISTANT', types: ['MATH', 'TEACHING'], duration: 'AUG 2026 – PRESENT', location: 'ORLANDO, FL', organization: 'UCF MATHEMATICS LAB', category: 'ACADEMIC ROLE', description: 'SUPPORTED STUDENTS ACROSS CALCULUS, PRECALCULUS, TRIGONOMETRY, AND ALGEBRA IN THE UCF MATH LAB.' },
  { number: '004', title: 'TEACHING ASSISTANT', types: ['CS', 'MENTORING'], duration: 'MAY 2025 – AUG 2026', location: 'ORLANDO, FL', organization: 'UCF DEPARTMENT OF CS', category: 'ACADEMIC ROLE', description: 'MENTORED 200+ STUDENTS PER TERM IN DATA STRUCTURES, ALGORITHMS, AND OBJECT-ORIENTED PROGRAMMING.' },
  { number: '005', title: 'UNDERGRADUATE RESEARCH ASSISTANT', types: ['RESEARCH', 'SYSTEMS'], duration: 'JAN 2025 – APR 2025', location: 'ORLANDO, FL', organization: 'UCF APPLESEED LAB', category: 'RESEARCH ROLE', description: 'PROTOTYPED WEB INTERFACES, APIS, AND AUTOMATED DELIVERY FLOWS WHILE EXPLORING LLM-ASSISTED ENGINEERING.' },
  { number: '006', title: 'GRADUATE ADMISSIONS BOARD', types: ['OPS', 'LEADERSHIP'], duration: 'AUG 2025 – DEC 2025', location: 'ORLANDO, FL', organization: 'TAU BETA PI HONOR SOCIETY', category: 'OPERATIONS ROLE', description: 'IMPROVED ADMISSIONS WORKFLOWS FOR INCOMING GRADUATE ENGINEERING CANDIDATES.' },
]
